os:
    - linux
language: node_js
node_js:
    - "8.15.1"
jdk:
    - oraclejdk8
addons:
    apt:
        packages:
            - oracle-java8-set-default
cache:
    yarn : true
    directories:
        - node_modules
        - $HOME/.m2
env:
    matrix:
        - JHIPSTER_VERSION=4.6.2
        - JHIPSTER_VERSION=4.13.3
        - JHIPSTER_VERSION=latest
    global:
        - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
before_install:
    - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - yarn global add yo
install:
    - yarn install
    - yarn test
    - yarn link
before_script:
    - rm -r test
script:
    - $JHIPSTER_TRAVIS/run-test-case.sh
notifications:
    email: false
